[package]
name = "mtb"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrayvec = "0.7.1"
include_path = "0.1.1"
lazy_static = "1.4.0"
macroquad = "0.3.10"
nanoserde = "0.1.29"
noise = "0.7.0"