name: MTB Master

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        target: wasm32-unknown-unknown
    - uses: Swatinem/rust-cache@v1
    - name: Build WASM
      run: cargo build --release --target wasm32-unknown-unknown
    - name: Setup DIST
      run: |
        rm -rf ./dist
        mkdir ./dist
        cp -R ./wasm/* ./dist/
        cp -R ./assets/ ./dist/assets/
        cp ./target/wasm32-unknown-unknown/release/mtb.wasm ./dist/
    - name: GitHub Pages
      uses: crazy-max/ghaction-github-pages@v2.5.0
      with:
        build_dir: ./dist/
        jekyll: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
