name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build-wasm
      run: cargo build --release --target wasm32-unknown-unknown
    - name: setup-dist
      run: |
        rm -rf ./dist
        mkdir ./dist
        cp -R ./wasm/* ./dist/
        cp ./target/wasm32-unknown-unknown/release/mbt.wasm ./dist/
    - name: GitHub Pages
      uses: crazy-max/ghaction-github-pages@v2.5.0
      with:
        build_dir: ./dist/
        jekyll: false
